defaults:
  - _self_
  - agent: cnn_off_policy_bs16
  - env: car_racing

hydra:
  run:
    dir: ${result_dir}/${now:%Y%m%d_%H%M%S}_${agent_type}_${exp_name}
  sweep:
    dir: ${result_dir}
    subdir: ${now:%Y%m%d_%H%M%S}_${agent_type}_${exp_name}

exp_name: default
result_dir: results
env_factory: null
trial_num: 1
seed: -1
render: 1
render_scale: 1.0
off_wandb: false
wandb_group: default_group

# training
episode_limit: 1_000_000_000
max_grad_norm: 5.0
sparsity: 0.0
gamma: 0.99
seq_len: 1
horizon: 1
buffer_device: cuda
critic_loss_weight: 1.0
use_done: 1
normalizing_by_return: 0
image_save_interval: 100
print_interval: 5
accumulation_steps: 1
max_step_count: 100
debug: false
