program: scripts/train.py
method: grid
parameters:
  env:
    value: placeholder
  agent:
    values: [cnn_off_policy_bs16, vlm_off_policy_bs16, vlm_off_policy_bs1, vlm_streaming]
  seed:
    values: [0]
command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - ${args_no_hyphens}
