program: scripts/train.py
method: grid
metric:
  name: total_average_score
  goal: maximize
parameters:
  som_alpha:
    values: [0.5, 1.0, 2.0]
  som_w:
    values: [10.0, 25.0, 50.0]
command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - agent=standard
  - network_class=actor_critic_with_action_value
  - learning_mode=off_policy
  - batch_size=16
  - actor_lr=1e-5
  - critic_lr=1e-5
  - env=car_racing
  - policy_type=som
  - step_limit=50_000
  - ${args_no_hyphens}
