# @package _global_
env_id: CARLA-Leaderboard-v0
episode_limit: 200
step_limit: 1_000_000
render_scale: 0.33
time_limit_hour: 2.0

env_factory:
  _target_: vla_streaming_rl.wrappers.make_carla_env

  route_id: 26950
  sequence_mode: random
  start_index: 0
  loop: true
  early_off_route_m: 10
  early_blocked_steps: 200
