# @package _global_
defaults:
  - base/network
  - base/off_policy
  - base/streaming
  - base/vlm
  - _self_

agent_type: standard
network_class: animal_world_critic_actor_critic
learning_mode: off_policy
batch_size: 16
seq_len: 8
actor_lr: 1e-5
critic_lr: 1e-5
buffer_device: cpu
buffer_size: 400_000
learning_starts: 4_000
