# @package _global_
defaults:
  - base_network
  - base_off_policy
  - base_streaming
  - base_cnn
  - base_vlm
  - _self_

agent_type: off_policy
network_class: actor_critic_with_action_value
batch_size: 16
learning_rate: 1e-5
