# @package _global_
defaults:
  - base_network
  - base_off_policy
  - base_streaming
  - base_cnn
  - base_vlm
  - _self_

agent_type: streaming
network_class: vlm_actor_critic_with_action_value
seq_len: 2
