# @package _global_
defaults:
  - base_network
  - base_off_policy
  - base_streaming
  - base_cnn
  - base_vlm
  - _self_

agent_type: off_policy
network_class: vlm_actor_critic_with_action_value
batch_size: 1
actor_lr: 2e-6
critic_lr: 2e-6
